test hardocing value

diff --git a/.github/workflows/test-dispatch.yml b/.github/workflows/test-dispatch.yml
--- a/.github/workflows/test-dispatch.yml
+++ b/.github/workflows/test-dispatch.yml
@@ -22,14 +22,14 @@ jobs:
       - name: Set workflow variables based on env
         id: vars
         run: |
-          case "dev" in
-          (local) echo "##[set-output name=DEPLOYMENT_PROJECT;]remo-local ;;
-          (dev) echo "##[set-output name=DEPLOYMENT_PROJECT;]remo-conference-dev ;;
-          (staging) echo "##[set-output name=DEPLOYMENT_PROJECT;]remo-conference-staging ;;
-          (qa) echo "##[set-output name=DEPLOYMENT_PROJECT;]remo-conference-qa ;;
-          (next) echo "##[set-output name=DEPLOYMENT_PROJECT;]remo-conference-next ;;
-          (live) echo "##[set-output name=DEPLOYMENT_PROJECT;]remo-conference ;;
-          (*) echo "Invalid environment" && exit 1 ;;
+          case dev in
+          local) echo "##[set-output name=DEPLOYMENT_PROJECT;]remo-local ;;
+          dev) echo "##[set-output name=DEPLOYMENT_PROJECT;]remo-conference-dev ;;
+          staging) echo "##[set-output name=DEPLOYMENT_PROJECT;]remo-conference-staging ;;
+          qa) echo "##[set-output name=DEPLOYMENT_PROJECT;]remo-conference-qa ;;
+          next) echo "##[set-output name=DEPLOYMENT_PROJECT;]remo-conference-next ;;
+          live) echo "##[set-output name=DEPLOYMENT_PROJECT;]remo-conference ;;
+          *) echo "Invalid environment" && exit 1 ;;
           esac
 
           ENVIRONMENT=$(echo ${{ github.event.inputs.environment }} | tr '[:lower:]' '[:upper:]')
